version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: azamat
      POSTGRES_PASSWORD: azamat-0840
      POSTGRES_DB: sentimentdb
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://azamat:azamat-0840@db/sentimentdb
      SECRET_KEY: your-secret-key

    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"